apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  labels:
    {{- include "nginx_k8s.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  ports:
    - nodePort: 30001
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
  selector:
    {{- include "nginx_k8s.labels" . | nindent 4 }} 